<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArchiveInventorySeeder extends Seeder
{
    public function run(): void
    {
        // Archive inventory rows are generated by archive procedures during lifecycle events.
    }
}
