<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AuditTrailSeeder extends Seeder
{
    public function run(): void
    {
        // Audit trail rows are generated by triggers and runtime actions.
    }
}
