<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page {
      margin: 50px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
      color: #111827;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 420px;
      margin-right: 10px;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin: 10px 0 2px 0;
    }

    .generated-date,
    .summary {
      text-align: center;
      margin-bottom: 8px;
    }

    .bibliography-list {
      margin: 12px 0 0 18px;
      padding: 0;
    }

    .bibliography-list li {
      margin-bottom: 10px;
      line-height: 1.6;
      text-align: justify;
      margin-left: 20px;
      font-weight: bold;
    }

    .empty-state {
      text-align: center;
      margin-top: 24px;
    }

    .user {
      text-align: right;
      padding-top: 24px;
      margin-right: 5px;
      font-size: 10px;
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Organization Logo">
    </div>
    <hr>
  </header>

  <h4 class="title">{{ $title }}</h4>
  @if(isset($schoolYear))
    <div style="text-align: center; font-size: 11px; font-weight: bold; margin-top: -2px; margin-bottom: 8px;">School Year {{ $schoolYear }}</div>
  @endif
  <div class="generated-date">{{ $date }}</div>

  <main>
    @if($data->isNotEmpty())
    <ul class="bibliography-list" style="list-style-type: none; padding-left: 0; margin-left: 0;">
      @foreach($data as $item)
      <li style="margin-left: 0; text-indent: 0;">{{ $item->bibliography_entry }}</li>
      @endforeach
    </ul>
    @else
    <p class="empty-state">No data found.</p>
    @endif
  </main>

  <div class="summary" style="margin-top: 20px; text-align: left; font-weight: bold;">Total Entries: {{ $totalCount }}</div>
  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = $pdf->get_width() - 80;
      $y = $pdf->get_height() - 20;
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>
