<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <style>
    @page {
      margin: 30px 25px 40px 25px;
      /* Top, Right, Bottom, Left */
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      /* safer than web fonts in DOMPDF */
      font-size: 10px;
      margin: 0;
      padding: 0;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 420px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2,
    p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 2px;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .table-container {
      width: 100%;
      overflow-x: hidden;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: auto;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 10px;
      word-break: break-word;
      text-align: left;
    }

    th {
      background-color: #cccccc;
      font-weight: bold;
      text-align: center;
    }

    /* Optional print adjustments */
    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Logo">
    </div>
    <hr>
  </header>

  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">{{ $date }}</div>
  <main class="table-container">
    <table>
      <thead>
        <tr>
          <th>Accession</th>
          <th>Author</th>
          <th>Title</th>
          <th>Publication</th>
          <th>Publisher</th>
          <th>Call Number</th>
          <th>ISBN</th>
          <th>Copyright</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
        <tr>
          <td>{{ $item->accession }}</td>
          <td>{{ $item->author ?? 'N/A' }}</td>
          <td>{{ $item->title }}</td>
          <td>{{ $item->place_of_publication ?? 'N/A' }}</td>
          <td>{{ $item->publisher ?? 'N/A' }}</td>
          <td>{{ $item->call_number ?? 'N/A' }}</td>
          <td>{{ $item->isbn ?? 'N/A' }}</td>
          <td>{{ $item->copyrights ?? 'N/A' }}</td>
          <td>{{ $item->remarks ?? 'N/A' }}</td>
        </tr>
        @empty
        <tr>
          <td colspan="9" style="text-align: center;">No data found.</td>
        </tr>
        @endforelse
      </tbody>
    </table>
  </main>
  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = $pdf->get_width() - 120;
      $y = $pdf->get_height() - 20;
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>