<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    @page {
      margin: 30px 25px 40px 25px; /* Top, Right, Bottom, Left */
    }

    body {
      font-family: 'DejaVu Sans', sans-serif; /* safer than web fonts in DOMPDF */
      font-size: 10px;
      margin: 0;
      padding: 0;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 420px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2, p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 2px;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .table-container {
      width: 100%;
      overflow-x: hidden;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }

    th {
      background-color: #cccccc;
      font-weight: bold;
      text-align: center;
    }

    /* Optional print adjustments */
    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Logo">
    </div>
    <hr>
  </header>

  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">{{ $date }}</div>
  <main class="table-container">
    <table>
      <thead>
        <tr>
          <th>Accession Number</th>
          <th>Call Number</th>
          <th>Title</th>
          <th>Category</th>
          <th>Availability</th>
          <th>Condition</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
          <tr>
            <td>{{ $item->accession }}</td>
            <td>{{ $item->call_number }}</td>
            <td>{{ $item->title }}</td>
            <td>{{ $item->category->name }}</td>
            <td>{{ $item->availability_status }}</td>
            <td>{{ $item->condition_status }}</td>
          </tr>
        @empty
          <tr>
            <td colspan="6" style="text-align: center;">No data found.</td>
          </tr>
        @endforelse
      </tbody>
    </table>
  </main>
  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pdf->page_text(520, 820, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>
</html>
