<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Computer Use Statistics Report</title>
  <style>
    @page {
      margin: 15mm 15mm 15mm 15mm;
    }

    body {
      font-family: Arial, sans-serif;
      font-size: 11px;
      color: #333;
      margin: 0;
      padding: 0;
    }

    .header-container {
      text-align: center;
      margin-bottom: 20px;
    }

    .header-logo {
      height: 70px;
      width: auto;
      display: inline-block;
    }

    .report-title {
      font-size: 13px;
      font-weight: bold;
      text-align: center;
      margin: 15px 0 5px 0;
      color: #111827;
    }

    .report-period {
      font-size: 10px;
      text-align: center;
      margin: 0 0 20px 0;
      color: #4b5563;
      font-style: italic;
    }

    .graph-container {
      text-align: center;
      margin-bottom: 30px;
    }

    .graph-image {
      max-width: 100%;
      height: auto;
      border: 1px solid #d1d5db;
      padding: 5px;
      background-color: #fff;
    }

    .summary-title {
      font-size: 11px;
      font-weight: bold;
      color: #374151;
      margin-bottom: 10px;
      text-transform: uppercase;
    }

    .data-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 30px;
    }

    .data-table th {
      background-color: #f3f4f6;
      border: 1px solid #d1d5db;
      padding: 8px 10px;
      font-weight: bold;
      text-align: left;
      text-transform: uppercase;
      font-size: 9px;
      color: #374151;
    }

    .data-table td {
      border: 1px solid #e5e7eb;
      padding: 7px 10px;
      vertical-align: top;
      color: #4b5563;
    }

    .data-table tr:nth-child(even) {
      background-color: #f9fafb;
    }

    .text-center {
      text-align: center;
    }

    .metadata-section {
      width: 100%;
      margin-top: 30px;
      border-collapse: collapse;
    }

    .metadata-cell {
      width: 50%;
      vertical-align: top;
      font-size: 10px;
      color: #4b5563;
    }

    .generated-by {
      font-weight: bold;
      margin-bottom: 5px;
    }

    .timestamp {
      color: #9ca3af;
      font-size: 9px;
    }

    .page-break {
      page-break-before: always;
    }
  </style>
</head>

<body>

  <!-- PAGE 1: GRAPH -->
  <div class="header-container">
    <img class="header-logo" src="data:image/png;base64,{{ $logo }}" alt="School Logo">
  </div>

  <h2 class="report-title">{{ $title }}</h2>
  <p class="report-period">{{ $date }}</p>

  <div class="graph-container">
    <img class="graph-image" src="{{ $graphImage }}" alt="Computer Use Chart">
  </div>

  <table class="metadata-section">
    <tr>
      <td class="metadata-cell">
        <div class="generated-by">Report Generated By: {{ $user }}</div>
      </td>
      <td class="metadata-cell" style="text-align: right; vertical-align: bottom;">
        <div style="color: #9ca3af; font-size: 9px;">Page 1 of 2</div>
      </td>
    </tr>
  </table>

  <!-- PAGE 2: HOURLY SUMMARY TABLE -->
  <div class="page-break"></div>

  <div class="header-container">
    <img class="header-logo" src="data:image/png;base64,{{ $logo }}" alt="School Logo">
  </div>

  <h2 class="report-title">{{ $title }}</h2>
  <p class="report-period">{{ $date }}</p>

  <h3 class="summary-title">Hourly Attendance Breakdowns</h3>
  <table class="data-table">
    <thead>
      <tr>
        <th>Hour</th>
        <th class="text-center">Total Attendance</th>
      </tr>
    </thead>
    <tbody>
      @forelse($tableData as $row)
      <tr>
        <td>{{ $row['hour'] }}</td>
        <td class="text-center">{{ number_format($row['count']) }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="2" class="text-center" style="color: #9ca3af; padding: 15px;">No attendance data found.</td>
      </tr>
      @endforelse
    </tbody>
  </table>

  <table class="metadata-section">
    <tr>
      <td class="metadata-cell">
        <div class="generated-by">Report Generated By: {{ $user }}</div>
      </td>
      <td class="metadata-cell" style="text-align: right; vertical-align: bottom;">
        <div style="color: #9ca3af; font-size: 9px;">Page 2 of 2</div>
      </td>
    </tr>
  </table>

</body>

</html>
