<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
      overflow-x: hidden;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 420px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2,
    p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 2px;
    }

    h4 {
      text-align: center;
      margin-top: 5px;
      margin-bottom: 3px;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .strikethrough {
      text-decoration: line-through;
      color: #6b7280;
    }

    .discounted {
      color: #15803d;
      font-weight: bold;
    }

    .discount-note {
      color: #15803d;
      font-size: 9px;
      margin-left: 4px;
    }

    .summary {
      width: 260px;
      margin-top: 12px;
      font-size: 10px;
    }

    .summary-row {
      display: table;
      width: 100%;
      margin-bottom: 3px;
    }

    .summary-label,
    .summary-value {
      display: table-cell;
    }

    .summary-value {
      text-align: right;
    }

    .summary-total {
      border-top: 1px solid #111827;
      padding-top: 4px;
      font-weight: bold;
    }

    .table-container {
      width: 100%;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: auto;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 10px;
      word-break: break-word;
      text-align: left;
    }

    th {
      background-color: #cccccc;
      font-weight: bold;
      text-align: center;
    }

    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="{{ $title }} Logo">
    </div>
    <hr>
  </header>

  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">{{ $date }}</div>

  <main class="table-container">
    <p>{{ $data->reporting_period }}</p>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Accession</th>
          <th>Book</th>
          <th>Borrowed</th>
          <th>Due</th>
          <th>Returned</th>
          <th>Violation</th>
          <th>Amount</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
        <tr>
          <td>{{ $item->user->first_name }} {{ $item->user->last_name }}</td>
          <td>{{ $item->book->accession }}</td>
          <td>{{ $item->book->title }}</td>
          <td>{{ $item->borrowed }}</td>
          <td>{{ $item->due }}</td>
          <td>{{ $item->returned }}</td>
          <td>{{ $item->violation ?? 'No Violation' }}</td>
          <td>
            @if($item->has_discount)
            <div class="strikethrough">PHP {{ number_format($item->actual_total ?? 0, 2) }}</div>
            <div><span class="discounted">PHP {{ number_format($item->total ?? 0, 2) }}</span><span class="discount-note">{{ $item->discount_percent_label }} discount</span></div>
            @else
            PHP {{ number_format($item->total ?? 0, 2) }}
            @endif
          </td>
          <td>{{ $item->status }}</td>
        </tr>
        @empty
        <tr>
          <td colspan="9" style="text-align: center;">No data found.</td>
        </tr>
        @endforelse
      </tbody>
    </table>
    <div class="summary">
      @foreach($summary['rows'] as $summaryRow)
      <div class="summary-row {{ $summaryRow['is_total'] ? 'summary-total' : '' }}">
        <div class="summary-label">{{ $summaryRow['label'] }}</div>
        <div class="summary-value">PHP {{ number_format($summaryRow['amount'], 2) }}</div>
      </div>
      @endforeach
    </div>
  </main>

  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = $pdf->get_width() - 80;
      $y = $pdf->get_height() - 20;
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>
