<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
      overflow-x: hidden;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 420px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2,
    p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 2px;
    }

    h4 {
      text-align: center;
      margin: 5px 0;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .table-container {
      width: 100%;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: auto;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 10px;
      word-break: break-word;
      text-align: left;
    }

    th {
      background-color: #cccccc;
      font-weight: bold;
      text-align: center;
    }

    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="{{ $title }} Logo">
    </div>
    <hr>
  </header>

  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">{{ $date }}</div>

  <main class="table-container">
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>User Name</th>
          <th>Grade & Section / Role</th>
          <th>Type</th>
          <th>Topic</th>
          <th>Title of Material</th>
          <th>Pages</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
        <tr>
          <td>{{ \Carbon\Carbon::parse($item->printed_at)->format('M j, Y') }}</td>
          <td>{{ \Carbon\Carbon::parse($item->printed_at)->format('g:i A') }}</td>
          <td>
            @if($item->student && $item->student->users)
              {{ $item->student->users->last_name }}, {{ $item->student->users->first_name }} {{ $item->student->users->middle_name }}
            @elseif($item->faculty && $item->faculty->users && !$item->student)
              {{ $item->faculty->users->last_name }}, {{ $item->faculty->users->first_name }} {{ $item->faculty->users->middle_name }}
            @else
              N/A
            @endif
          </td>
          <td>
            @if($item->student)
              {{ $item->student->level }} - {{ $item->student->section }}
            @elseif($item->faculty && !$item->student)
              {{ $item->faculty->employee_role }}
            @else
              N/A
            @endif
          </td>
          <td style="text-transform: capitalize;">{{ $item->type }}</td>
          <td>{{ $item->topic }}</td>
          <td>{{ $item->title_of_material ?? 'N/A' }}</td>
          <td style="text-align: center;">{{ $item->pages }}</td>
          <td>
            @if(isset($item->amount))
              ₱{{ number_format($item->amount, 2) }}
            @else
              N/A
            @endif
          </td>
        </tr>
        @empty
        <tr>
          <td colspan="9" style="text-align: center;">No printing/photocopy entries found.</td>
        </tr>
        @endforelse
      </tbody>
    </table>
  </main>

  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = $pdf->get_width() - 80;
      $y = $pdf->get_height() - 20;
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>
