<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
      overflow-x: hidden;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 500px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2,
    p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-bottom: 2px;
    }

    .semi-title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
    }

    h4 {
      text-align: center;
      margin-top: 5px;
      margin-bottom: 3px;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .table-container {
      width: 100%;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 10px;
      word-break: break-word;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }

    .total {
      font-weight: bold;
      text-align: right;
    }

    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="{{ $settings->org_initial }} Logo">
    </div>
    <hr>
  </header>
  <p class="semi-title">The Library</p>
  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">{{ $date }}</div>

  <main class="table-container">
    <table>
      <thead>
        <tr>
          <th>Legend</th>
          <th>Description</th>
          <th>Previous Inventory</th>
          <th>Newly Acquired</th>
          <th>Discarded</th>
          <th>Present Inventory</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
        <tr>
          <td>{{ $item->legend }}</td>
          <td>{{ $item->name }}</td>
          <td>{{ $item->previous_inventory }}</td>
          <td>{{ $item->newly_acquired }}</td>
          <td>{{ $item->discarded }}</td>
          <td>{{ $item->present_inventory }}</td>
        </tr>
        @empty
        <tr>
          <td colspan="6" style="text-align: center;">No data found.</td>
        </tr>
        @endforelse
        <tr>
          <td colspan="2" class="total">Total:</td>
          <td class="total">{{ $data->sum('previous_inventory') }}</td>
          <td class="total">{{ $data->sum('newly_acquired') }}</td>
          <td class="total">{{ $data->sum('discarded') }}</td>
          <td class="total">{{ $data->sum('present_inventory') }}</td>
        </tr>
      </tbody>
    </table>
  </main>

  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = 500;
      $y = 820; // Adjust this if needed
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>
