<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
      overflow-x: hidden;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 500px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2,
    p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-bottom: 2px;
    }

    .semi-title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
    }

    h4 {
      text-align: center;
      margin-top: 5px;
      margin-bottom: 3px;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .table-container {
      width: 100%;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: auto;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 10px;
      word-break: break-word;
      text-align: left;
    }

    th {
      background-color: #cccccc;
      font-weight: bold;
      text-align: center;
    }

    .left-col {
      text-align: left;
    }

    .center-col {
      text-align: center;
    }

    .total {
      font-weight: bold;
      text-align: right;
    }

    .total.center-col {
      text-align: center;
    }

    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="{{ $title }} Logo">
    </div>
    <hr>
  </header>
  <p class="semi-title">The Library</p>
  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">{{ $date }}</div>

  <main class="table-container">
    <table>
      <thead>
        <tr>
          <th class="left-col">Legend</th>
          <th class="left-col">Description</th>
          <th class="center-col">Previous Inventory</th>
          <th class="center-col">Newly Acquired</th>
          <th class="center-col">Lost and Paid For</th>
          <th class="center-col">Lost and Replaced</th>
          <th class="center-col">Unreturned</th>
          <th class="center-col">Missing</th>
          <th class="center-col">Discarded</th>
          <th class="center-col">Present Inventory</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
        <tr>
          <td class="left-col">{{ $item->legend }}</td>
          <td class="left-col">{{ $item->name }}</td>
          <td class="center-col">{{ $item->previous_inventory }}</td>
          <td class="center-col">{{ $item->newly_acquired }}</td>
          <td class="center-col">{{ $item->lost_and_paid_for }}</td>
          <td class="center-col">{{ $item->lost_and_replaced }}</td>
          <td class="center-col">{{ $item->unreturned }}</td>
          <td class="center-col">{{ $item->missing }}</td>
          <td class="center-col">{{ $item->discarded }}</td>
          <td class="center-col">{{ $item->present_inventory }}</td>
        </tr>
        @empty
        <tr>
          <td colspan="10" style="text-align: center;">No data found.</td>
        </tr>
        @endforelse
        <tr>
          <td colspan="2" class="total">Total:</td>
          <td class="total center-col">{{ $data->sum('previous_inventory') }}</td>
          <td class="total center-col">{{ $data->sum('newly_acquired') }}</td>
          <td class="total center-col">{{ $data->sum('lost_and_paid_for') }}</td>
          <td class="total center-col">{{ $data->sum('lost_and_replaced') }}</td>
          <td class="total center-col">{{ $data->sum('unreturned') }}</td>
          <td class="total center-col">{{ $data->sum('missing') }}</td>
          <td class="total center-col">{{ $data->sum('discarded') }}</td>
          <td class="total center-col">{{ $data->sum('present_inventory') }}</td>
        </tr>
      </tbody>
    </table>
  </main>

  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = $pdf->get_width() - 120;
      $y = $pdf->get_height() - 20;
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>