<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ $title }}</title>
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 300px;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin: 10px 0 5px 0;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      margin-top: 20px;
      font-size: 10px;
    }

    .section-title {
      font-size: 12px;
      font-weight: bold;
      margin-top: 20px;
      margin-bottom: 5px;
      background-color: #f2f2f2;
      padding: 5px;
      border: 1px solid #ddd;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 10px;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 6px 4px;
      font-size: 10px;
      text-align: left;
    }

    th {
      background-color: #f9f9f9;
      font-weight: bold;
    }

    .text-center {
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Logo">
    </div>
    <hr>
  </header>

  <div class="title">{{ $title }}</div>
  <div class="generated-date">{{ $range }}</div>
  <div class="generated-date">Generated on: {{ $date }}</div>

  @forelse($results as $sectionData)
    <div class="section-title">{{ $sectionData['section_title'] ?? ('Section ' . $sectionData['section']) }}</div>
    <table>
      <thead>
        <tr>
          <th style="width: 10%;" class="text-center">Rank</th>
          <th style="width: 50%;">Student Name</th>
          <th style="width: 20%;" class="text-center">Borrowed Books</th>
          <th style="width: 20%;">Grade</th>
        </tr>
      </thead>
      <tbody>
        @foreach($sectionData['students'] as $index => $student)
          <tr>
            <td class="text-center">{{ $index + 1 }}</td>
            <td>{{ trim($student->last_name . ', ' . $student->first_name . ' ' . $student->middle_name) }}</td>
            <td class="text-center">{{ $student->borrow_count }}</td>
            <td>{{ $sectionData['level_label'] ?? ('Grade ' . ($student->students->level == 'NURSERY' ? 'Nursery' : ($student->students->level == 'KINDERGARTEN' ? 'Kindergarten' : ucwords($student->students->level) ?? '-'))) }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  @empty
    <p class="text-center">No borrowed book data found for the selected period.</p>
  @endforelse

  <div class="user">Generated by: {{ $user }}</div>
</body>
</html>
