<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
      overflow-x: hidden;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 500px;
      margin-right: 10px;
    }

    .school-info {
      text-align: center;
    }

    h2,
    p {
      margin: 0;
      padding: 0;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 2px;
    }

    h4 {
      text-align: center;
      margin-top: 5px;
      margin-bottom: 3px;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      padding-top: 40px;
      margin-top: 10px;
      margin-right: 5px;
      font-size: 10px;
    }

    .table-container {
      width: 100%;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 10px;
      word-break: break-word;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }

    @media print {
      table {
        page-break-inside: auto;
      }

      tr {
        page-break-inside: avoid;
        page-break-after: auto;
      }
    }
  </style>
  <title>{{ $title }}</title>
</head>

<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="BPS Logo">
    </div>
    <hr>
  </header>

  <h4 class="title">{{ $title }}</h4>
  <div class="generated-date">Generated on: {{ $date }}</div>

  <main class="table-container">
    <table>
      <thead>
        <tr>
          <th>Accession Number</th>
          <th>Title</th>
          <th>Name</th>
          @if($type === 'Reserved' || $type === 'All')
          <th>Reserved Date</th>
          <th>Pickup Deadline</th>
          @endif
          @if($type === 'Borrowed' || $type === 'All')
          <th>Borrowed</th>
          <th>Due</th>
          <th>Returned</th>
          @endif
          <th>Transaction Type</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        @forelse($data as $item)
        @if($item->book && $item->user)
        <tr>
          <td>{{ $item->book->accession }}</td>
          <td>{{ $item->book->title }}</td>
          <td>{{ $item->user->last_name }}, {{ $item->user->first_name }} {{ $item->user->middle_name ?? '' }}</td>
          @if($type === 'Reserved' || $type === 'All')
          <td>{{ $item->reserved_date ?? 'N/A' }}</td>
          <td>{{ $item->pickup_deadline ?? 'N/A' }}</td>
          @endif
          @if($type === 'Borrowed' || $type === 'All')
          <td>{{ $item->date_borrowed ?? 'N/A' }}</td>
          <td>{{ $item->due_date ?? 'N/A' }}</td>
          <td>{{ $item->return_date ?? 'N/A' }}</td>
          @endif
          <td>{{ $item->transaction_type }}</td>
          <td>{{ $item->status }}</td>
        </tr>
        @endif
        @empty
        <tr>
          <td colspan="7" style="text-align: center;">No data found.</td>
        </tr>
        @endforelse
      </tbody>
    </table>
  </main>

  <div class="user">Generated by: {{ $user }}</div>

  @if (!app()->runningInConsole())
  @php ob_start(); @endphp
  <script type="text/php">
    if (isset($pdf)) {
      $font = $fontMetrics->getFont("DejaVu Sans", "normal");
      $size = 9;
      $pageText = "Page {PAGE_NUM} of {PAGE_COUNT}";
      $x = 930;
      $y = 580;
      $pdf->page_text($x, $y, $pageText, $font, $size);
    }
  </script>
  @php echo ob_get_clean(); @endphp
  @endif
</body>

</html>