<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ $title }}</title>
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      margin: 0;
      padding: 0;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }

    .logo img {
      max-width: 300px;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin: 10px 0 5px 0;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      margin-top: 20px;
      font-size: 10px;
    }

    img.chart {
      margin: 0 auto;
      margin-top: 10px;
      width: 100%;
      max-height: 380px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 15px;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 6px 4px;
      font-size: 8px;
      text-align: center;
    }

    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }

    .page-break {
      page-break-before: always;
    }
  </style>
</head>
<body>
  <!-- Page 1: Graph -->
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Logo">
    </div>
    <hr>
  </header>

  <div class="title">{{ $title }}</div>
  <div class="generated-date">{{ $date }}</div>
  
  <p style="text-align: center; font-size: 10px; font-weight: bold;">{{ $range }}</p>
  
  <div style="text-align: center;">
    <img class="chart" src="{{ $chart }}" alt="Chart">
  </div>

  <div class="user">Generated by: {{ $user }}</div>

  <!-- Page Break to separate Graph from Tabular Report -->
  <div class="page-break"></div>

  <!-- Page 2: Tabular Report -->
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Logo">
    </div>
    <hr>
  </header>

  <div class="title">Attendance Monitoring Summary (Hourly Breakdown)</div>
  <div class="generated-date">{{ $date }}</div>
  
  <p style="text-align: center; font-size: 10px; font-weight: bold;">{{ $range }}</p>

  <table>
    <thead>
      <tr>
        <th style="text-align: left; padding-left: 8px;">Date</th>
        @for ($h = 6; $h <= 21; $h++)
          <th>{{ $h == 12 ? '12:00 PM' : ($h > 12 ? ($h - 12) . ':00 PM' : $h . ':00 AM') }}</th>
        @endfor
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      @forelse($hourlyData as $dateStr => $hours)
        <tr>
          <td style="text-align: left; padding-left: 8px; white-space: nowrap;">{{ $dateStr }}</td>
          @php $rowTotal = 0; @endphp
          @for ($h = 6; $h <= 21; $h++)
            @php 
              $count = $hours[$h] ?? 0;
              $rowTotal += $count;
            @endphp
            <td>{{ $count > 0 ? $count : '-' }}</td>
          @endfor
          <td style="font-weight: bold;">{{ $rowTotal }}</td>
        </tr>
      @empty
        <tr>
          <td colspan="18">No data found.</td>
        </tr>
      @endforelse
    </tbody>
  </table>

  <div class="user" style="margin-top: 40px;">Generated by: {{ $user }}</div>
</body>
</html>
