<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ $title }}</title>
  <style>
    @page {
      margin: 30px 25px 40px 25px;
    }

    body {
      font-family: 'DejaVu Sans', sans-serif;
      font-size: 10px;
      display: flex;
      flex-direction: column;
      align-items: center;
      margin: 0;
      padding: 0;
    }

    header {
      text-align: center;
      margin-bottom: 10px;
    }
    main {
      width: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .logo img {
      max-width: 300px;
    }

    .title {
      text-align: center;
      font-size: 14px;
      font-weight: bold;
      margin: 10px 0 5px 0;
    }

    .generated-date {
      text-align: center;
      margin-bottom: 10px;
    }

    .user {
      text-align: right;
      margin-top: 40px;
      font-size: 10px;
    }

    img.chart {
      margin: 0 auto;
      margin-top: 30px;
      width: 100%;
    }
  </style>
</head>
<body>
  <header>
    <div class="logo">
      <img src="data:image/png;base64,{{ $logo }}" alt="Logo">
    </div>
    <hr>
  </header>

  <div class="title">{{ $title }}</div>
  <div class="generated-date">{{ $date }}</div>
  <main>
    <p>{{ $range }}</p>
    <img class="chart" src="{{ $chart }}" alt="Chart">
  </main>

  <div class="user">Generated by: {{ $user }}</div>
</body>
</html>
