<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Models\Category;
use Dompdf\Dompdf;
use Dompdf\Options;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as WriterXlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class CategoriesController extends Controller
{
    public function index()
    {
        $data = Category::all();
        return view('report.categories.categories', compact('data'));
    }
    public function export(Request $request)
    {
        $data = Category::all();
        if ($request->input('submit') == 'pdf') {
            $this->generatePDF($data);
            return redirect()->back()->with('toast-success', 'PDF generated successfully');
        } else if ($request->input('submit') == 'excel') {
            $this->exportExcel($data);
            return redirect()->back()->with('toast-success', 'Excel generated successfully');
        }
        return redirect()->back()->with('toast-warning', 'Invalid export type');
    }
    private function generatePDF($data)
    {
        $items = [
            'title'         => 'Summary of BPS Collections Report',
            'school'        => "Bicutan Parochial School, Inc.",
            'address'       => "Manuel L. Quezon St., Lower Bicutan, Taguig City",
            'logo'          => base64_encode(file_get_contents((public_path('img/BPSLogoFull.png')))),
            'user'          => Auth::user()->first_name . ' ' . Auth::user()->last_name,
            'date'          => date('F j, Y'),
            'data'          => $data,
            'totalCount'    => $data->count(),
        ];
        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isPhpEnabled', true);
        $options->set('isRemoteEnabled', true);
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml(view('pdf.summary-pdf-report', $items));
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        $dompdf->stream('book-summary-report ' . date('Y-m-d') . '.pdf', array('Attachment' => true));
        exit;
    }
    private function exportExcel($data)
    {
        $spreadsheet    = new Spreadsheet();
        $logo           = new Drawing();
        $sheet          = $spreadsheet->getActiveSheet();
        
        $logo->setName('BPS Logo');
        $logo->setDescription('BPS Logo');
        $logo->setPath(public_path('img/BPSLogoFull.png'));
        $logo->setHeight(80);
        $logo->setCoordinates('C1');
        $logo->setOffsetX(10);
        $logo->setOffsetY(5);
        $logo->setWorksheet($sheet);

        $sheet->setTitle('BPS Collection Report');
        $sheet->getColumnDimension('A')->setWidth(30);
        $sheet->getColumnDimension('B')->setWidth(30);
        $sheet->getColumnDimension('C')->setWidth(30);
        $sheet->getColumnDimension('D')->setWidth(30);
        $sheet->getColumnDimension('E')->setWidth(30);
        $sheet->getColumnDimension('F')->setWidth(30);
        $sheet->mergeCells('A7:F7');
        $sheet->mergeCells('A8:F8');
        $sheet->setCellValue('A7', 'Report Generated By: ' . Auth::user()->first_name . ' ' . Auth::user()->last_name);
        $sheet->setCellValue('A8', 'Report Generated On: ' . date('F j, Y'));
        $sheet->getStyle('A7:F8')->getFont()->setBold(true);
        $sheet->getStyle('A7:F8')->getFont()->setSize(10);
        $sheet->getStyle('A7:F8')->getAlignment()->setHorizontal('left');
        $sheet->getStyle('A7:F8')->getAlignment()->setVertical('left');
        $sheet->getStyle('A7:F8')->getAlignment()->setWrapText(true);
        $sheet->getStyle('A10:F10')->getFont()->setSize(12);
        $sheet->getStyle('A10:F10')->getFont()->setBold(true);
        $sheet->setCellValue('A10', 'Legend');
        $sheet->setCellValue('B10', 'Description');
        $sheet->setCellValue('C10', 'Previous Inventory');
        $sheet->setCellValue('D10', 'Newly Acquired');
        $sheet->setCellValue('E10', 'Discarded');
        $sheet->setCellValue('F10', 'Present Inventory');
        $row = 11;
        foreach ($data as $item) {
            $sheet->setCellValue('A' . $row, $item->legend);
            $sheet->setCellValue('B' . $row, $item->name);
            $sheet->setCellValue('C' . $row, $item->previous_inventory);
            $sheet->setCellValue('D' . $row, $item->newly_acquired);
            $sheet->setCellValue('E' . $row, $item->discarded);
            $sheet->setCellValue('F' . $row, $item->present_inventory);
            $sheet->getStyle('A' . $row . ':F' . $row)->getAlignment()->setHorizontal('left');
            $sheet->getStyle('A' . $row . ':F' . $row)->getAlignment()->setVertical('center');
            $sheet->getStyle('A' . $row . ':F' . $row)->getAlignment()->setWrapText(true);
            $row++;
        }
        $sheet->mergeCells('A' . $row . ':B' . $row);
        $sheet->getStyle('A' . $row . ':F' . $row)->getFont()->setSize(12);
        $sheet->getStyle('A' . $row . ':F' . $row)->getAlignment()->setHorizontal('right');
        $sheet->getStyle('A' . $row . ':F' . $row)->getFont()->setBold(true);
        $sheet->setCellValue('A' . $row, 'Total:');
        $sheet->setCellValue('C' . $row, $data->sum('previous_inventory'));
        $sheet->setCellValue('D' . $row, $data->sum('newly_acquired'));
        $sheet->setCellValue('E' . $row, $data->sum('discarded'));
        $sheet->setCellValue('F' . $row, $data->sum('present_inventory'));
        $writer     = new WriterXlsx($spreadsheet);
        $fileName = 'Collection-report ' . date('Y-m-d') . '.xlsx';
        header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        header("Content-Disposition: attachment;filename=\"$fileName\"");
        $writer->save("php://output");
        exit();
    }
    public function update(){
        try{
            DB::statement('CALL update_summary_matrix()');
        } catch (\Illuminate\Database\QueryException $e) {
            return redirect()->back()->with('toast-error', 'Error code: ' . $e->getMessage());
        }
        return redirect()->back()->with('toast-success', 'Successfully updated');
    }
}
