<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Inventory;
use Illuminate\Support\Facades\DB;
use DateTime;
use Dompdf\Dompdf;
use Dompdf\Options;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as WriterXlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class InventoriesController extends Controller
{
    public function index(){
        $fromInputDate  = null;
        $toInputDate    = null;
        $data           = Inventory::with('book')->orderBy('created_at', 'desc')->get();
        return view('report.inventories.index', compact('fromInputDate', 'toInputDate', 'data'));
    }
    public function search(Request $request){
        $fromInputDate  = $request->input('start');
        $toInputDate    = $request->input('end');
        $start          = null;
        $end            = null;
        $data           = Inventory::with('book')->where('checked_at', '!=', null)->orderBy('created_at', 'desc')->get();
        if(strlen($fromInputDate) > 0) $start = DateTime::createFromFormat('m/d/Y', $request->input('start'))->format('Y-m-d');
        if(strlen($toInputDate) > 0) $end = DateTime::createFromFormat('m/d/Y', $request->input('end'))->format('Y-m-d');
        if(strlen($fromInputDate) > 0 || strlen($toInputDate) > 0){
            $data = Inventory::with('book')->where('checked_at', '!=', null)->whereBetween(DB::raw('DATE(bk_inventories.checked_at)'), [$start, $end])->get();
        }
        if ($request->input('submit') == 'pdf') {
            $this->generatePDF($data);
            return redirect()->back()->with('toast-success', 'PDF generated successfully');
        }
        if ($request->input('submit') == 'excel') {
            $this->exportExcel($data);
            return redirect()->back()->with('toast-success', 'Excel generated successfully');
        }
        return view('report.inventories.index', compact('fromInputDate', 'toInputDate', 'data'));
    }
    private function generatePDF($data)
    {
        $items = [
            'title'         => 'Inventory Report',
            'school'        => "Bicutan Parochial School, Inc.",
            'address'       => "Manuel L. Quezon St., Lower Bicutan, Taguig City",
            'logo'          => base64_encode(file_get_contents((public_path('img/BPSLogoFull.png')))),
            'user'          => Auth::user()->first_name . ' ' . Auth::user()->last_name,
            'date'          => date('F j, Y'),
            'data'          => $data,
            'totalCount'    => $data->count(),
        ];
        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isPhpEnabled', true);
        $options->set('isRemoteEnabled', true);
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml(view('pdf.inventory-pdf-report', $items));
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        $dompdf->stream('inventory-report ' . date('Y-m-d') . '.pdf', array('Attachment' => true));
        exit;
    }
    private function exportExcel($data)
    {
        $spreadsheet    = new Spreadsheet();
        $logo           = new Drawing();
        $sheet          = $spreadsheet->getActiveSheet();
        
        $logo->setName('BPS Logo');
        $logo->setDescription('BPS Logo');
        $logo->setPath(public_path('img/BPSLogoFull.png'));
        $logo->setHeight(80);
        $logo->setCoordinates('C1');
        $logo->setOffsetX(10);
        $logo->setOffsetY(5);
        $logo->setWorksheet($sheet);

        $sheet->setTitle('Book Circulation Report');
        $sheet->getColumnDimension('A')->setWidth(20);
        $sheet->getColumnDimension('B')->setWidth(30);
        $sheet->getColumnDimension('C')->setWidth(60);
        $sheet->getColumnDimension('D')->setWidth(30);
        $sheet->getColumnDimension('E')->setWidth(30);
        $sheet->mergeCells('A7:E7');
        $sheet->mergeCells('A8:E8');
        $sheet->setCellValue('A7', 'Report Generated By: ' . Auth::user()->first_name . ' ' . Auth::user()->last_name);
        $sheet->setCellValue('A8', 'Report Generated On: ' . date('F j, Y'));
        $sheet->getStyle('A7:E8')->getFont()->setBold(true);
        $sheet->getStyle('A7:E8')->getFont()->setSize(10);
        $sheet->getStyle('A7:E8')->getAlignment()->setHorizontal('left');
        $sheet->getStyle('A7:E8')->getAlignment()->setVertical('left');
        $sheet->getStyle('A7:E8')->getAlignment()->setWrapText(true);
        $sheet->getStyle('A10:E10')->getFont()->setSize(12);
        $sheet->getStyle('A10:E10')->getFont()->setBold(true);
        $sheet->setCellValue('A10', 'Accession Number');
        $sheet->setCellValue('B10', 'Call Number');
        $sheet->setCellValue('C10', 'Title');
        $sheet->setCellValue('D10', 'Author');
        $sheet->setCellValue('E10', 'Last Inventory');
        $row = 11;
        foreach ($data as $item) {
            $sheet->setCellValue('A' . $row, $item->book->accession);
            $sheet->setCellValue('B' . $row, $item->book->call_number);
            $sheet->setCellValue('C' . $row, $item->book->title);
            $sheet->setCellValue('D' . $row, $item->book->author);
            $sheet->setCellValue('E' . $row, Carbon::parse($item->checked_at)->format('m/d/Y'));
            $row++;
        }
        $writer     = new WriterXlsx($spreadsheet);
        $fileName = 'inventory-report ' . date('Y-m-d') . '.xlsx';
        header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        header("Content-Disposition: attachment;filename=\"$fileName\"");
        $writer->save("php://output");
        exit;
    }
}
