<?php

namespace App\Http\Controllers\Report;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Support\Facades\Validator;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as WriterXlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Models\Penalty;
use Illuminate\Support\Facades\Auth;
use Svg\Tag\Rect;

class PenaltiesController extends Controller
{
    public function index(Request $request)
    {
        $search         = $request->input('search');
        $fromInputDate  = $request->input('start');
        $toInputDate    = $request->input('end');
        $perPage        = $request->input('perPage', 10);
        $data           = $this->generateData($request);
        return view('report.penalties.index', compact('data', 'fromInputDate', 'toInputDate', 'search', 'perPage'));
    }
    public function search(Request $request)
    {
        $search         = $request->input('search');
        $fromInputDate  = $request->input('start');
        $toInputDate    = $request->input('end');
        $perPage        = $request->input('perPage', 10);
        $validator = Validator::make($request->all(), [
            'start'         => 'nullable|date',
            'end'           => 'nullable|date',
            'search'        => 'nullable',
            'perPage'       => 'nullable|numeric|in:10,25,50'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->with('toast-warning', $validator->errors()->first());
        }
        if ($request->input('submit') == 'pdf') {
            $data = $this->generateData($request, true);
            $this->generatePDF($data);
            return redirect()->route('report.penalties')->with('toast-success', 'Successfully exported to PDF');
        } else if ($request->input('submit') == 'excel') {
            $data = $this->generateData($request, true);
            $this->exportExcel($data);
            return redirect()->route('report.penalties')->with('toast-success', 'Successfully exported to Excel');
        }
        $data = $this->generateData($request, false);
        return view('report.penalties.index', compact('data', 'search', 'fromInputDate', 'toInputDate', 'perPage'));
    }
    private function generatePDF($data)
    {
        $items = [
            'title'         => 'Overdue Fines Report',
            'school'        => "Bicutan Parochial School, Inc.",
            'address'       => "Manuel L. Quezon St., Lower Bicutan, Taguig City",
            'logo'          => base64_encode(file_get_contents((public_path('img/BPSLogoFull.png')))),
            'user'          => Auth::user()->first_name . ' ' . Auth::user()->last_name,
            'date'          => date('F j, Y'),
            'data'          => $data,
            'totalCount'    => $data->count(),
        ];
        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isPhpEnabled', true);
        $options->set('isRemoteEnabled', true);
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml(view('pdf.penalties-pdf-report', $items));
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        $dompdf->stream('overdue-fines-report ' . date('Y-m-d') . '.pdf', array('Attachment' => true));
        exit;
    }
    private function exportExcel($data)
    {
        $spreadsheet    = new Spreadsheet();
        $logo           = new Drawing();
        $sheet          = $spreadsheet->getActiveSheet();
        
        $logo->setName('BPS Logo');
        $logo->setDescription('BPS Logo');
        $logo->setPath(public_path('img/BPSLogoFull.png'));
        $logo->setHeight(80);
        $logo->setCoordinates('C1');
        $logo->setOffsetX(90);
        $logo->setOffsetY(5);
        $logo->setWorksheet($sheet);

        $sheet->setTitle('Overdue Fines Report');
        $sheet->getColumnDimension('A')->setWidth(30);
        $sheet->getColumnDimension('B')->setWidth(20);
        $sheet->getColumnDimension('C')->setWidth(60);
        $sheet->getColumnDimension('D')->setWidth(20);
        $sheet->getColumnDimension('E')->setWidth(20);
        $sheet->getColumnDimension('F')->setWidth(20);
        $sheet->getColumnDimension('G')->setWidth(20);
        $sheet->getColumnDimension('H')->setWidth(20);
        $sheet->getColumnDimension('I')->setWidth(20);
        $sheet->mergeCells('A7:I7');
        $sheet->mergeCells('A8:I8');
        $sheet->setCellValue('A7', 'Report Generated By: ' . Auth::user()->first_name . ' ' . Auth::user()->last_name);
        $sheet->setCellValue('A8', 'Report Generated On: ' . date('F j, Y'));
        $sheet->getStyle('A7:I8')->getFont()->setBold(true);
        $sheet->getStyle('A7:I8')->getFont()->setSize(10);
        $sheet->getStyle('A7:I8')->getAlignment()->setHorizontal('left');
        $sheet->getStyle('A7:I8')->getAlignment()->setVertical('left');
        $sheet->getStyle('A7:I8')->getAlignment()->setWrapText(true);
        $sheet->getStyle('A10:I10')->getFont()->setSize(12);
        $sheet->getStyle('A10:I10')->getFont()->setBold(true);
        $sheet->setCellValue('A10', 'Name');
        $sheet->setCellValue('B10', 'Accession');
        $sheet->setCellValue('C10', 'Book');
        $sheet->setCellValue('D10', 'Borrowed Date');
        $sheet->setCellValue('E10', 'Due Date');
        $sheet->setCellValue('F10', 'Returned Date');
        $sheet->setCellValue('G10', 'Violation');
        $sheet->setCellValue('H10', 'Amount');
        $sheet->setCellValue('I10', 'Status');
        $row = 11;
        foreach ($data as $item) {
            if(!$item->transaction->user || !$item->transaction->book || !$item->penaltyRule) {
                continue; // Skip if users relationship is not loaded
            }
            $sheet->setCellValue('A' . $row, $item->transaction->user->first_name . ' ' . $item->transaction->user->last_name);
            $sheet->setCellValue('B' . $row, $item->transaction->book->accession);
            $sheet->setCellValue('C' . $row, $item->transaction->book->title);
            $sheet->setCellValue('D' . $row, $item->transaction->date_borrowed);
            $sheet->setCellValue('E' . $row, $item->transaction->due_date ?? 'Not Returned');
            $sheet->setCellValue('F' . $row, $item->transaction->return_date ?? 'Not Returned');
            $sheet->setCellValue('G' . $row, $item->penaltyRule->type);
            $sheet->setCellValue('H' . $row, $item->amount);
            $sheet->setCellValue('I' . $row, $item->transaction->penalty_status);

            $row++;
        }
        $writer     = new WriterXlsx($spreadsheet);
        $fileName = 'penalties-report ' . date('Y-m-d') . '.xlsx';
        header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        header("Content-Disposition: attachment;filename=\"$fileName\"");
        $writer->save("php://output");
        exit;
    }
    private function generateData(Request $request, bool $isExport = false)
    {
        $fromInputDate  = $request->input('start');
        $toInputDate    = $request->input('end');
        $search         = strtolower($request->input('search'));
        $perPage        = $request->input('perPage', 10);
        $query = Penalty::with([
            'penaltyRule',
            'transaction.user',
            'transaction.book'
        ]);

        // Date filter (created_at column from penalties table)
        if (!empty($fromInputDate) && !empty($toInputDate)) {
            $from = Carbon::createFromFormat('m/d/Y', $fromInputDate)->format('Y-m-d');
            $to = Carbon::createFromFormat('m/d/Y', $toInputDate)->format('Y-m-d');

            $query->whereBetween(DB::raw('DATE(tr_penalties.created_at)'), [$from, $to]);
        }

        // Name search through transaction.user
        if (!empty($search)) {
            $query->whereHas('transaction.user', function ($q) use ($search) {
                $q->where(DB::raw('LOWER(first_name)'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(last_name)'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(middle_name)'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(CONCAT(first_name, " ", middle_name, " ", last_name))'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(CONCAT(middle_name, " ", last_name, ", ", first_name))'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(CONCAT(last_name, ", ", first_name, " ", middle_name))'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(CONCAT(last_name, ", ", first_name))'), 'like', '%' . $search . '%')
                ->orWhere(DB::raw('LOWER(CONCAT(first_name, " ", last_name))'), 'like', '%' . $search . '%');
            });
        }
        if($isExport) {
            $data = $query->orderBy(DB::raw('DATE(tr_penalties.created_at)'), 'desc')->get();
            $minDate = $data->min(fn($item) => \Carbon\Carbon::parse($item->created_at));
            $maxDate = $data->max(fn($item) => \Carbon\Carbon::parse($item->created_at));
            if ($minDate && $maxDate) {
                $data->reporting_period = $minDate->format('F j, Y') . ' to ' . $maxDate->format('F j, Y');
            } else {
                $data->reporting_period = 'N/A';
            }
        } else {
            $data = $query->orderBy(DB::raw('DATE(tr_penalties.created_at)'), 'desc')
                ->paginate($perPage)
                ->appends([
                    'start' => $fromInputDate,
                    'end' => $toInputDate,
                    'search' => $search,
                    'perPage' => $perPage
                ]);
        }

        return $data;
    }
}
