<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Transaction;
use DateTime;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as WriterXlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Dompdf\Dompdf;
use Dompdf\Options;

class TransactionController extends Controller
{
    public function index()
    {
        $fromInputDate  = "";
        $toInputDate    = "";
        $inputName      = "";
        $inputLastName  = "";
        $type           = "All";
        $data           = Transaction::with('book', 'user')
            ->orderBy(DB::raw('DATE(date_borrowed)'), 'desc')
            ->orderBy(DB::raw('TIME(date_borrowed)'), 'desc')
            ->get();
        return view('report.transactions.transactions', compact('data', 'inputName', 'inputLastName', 'fromInputDate', 'toInputDate', 'type'));
    }
    public function test()
    {
        $data           = Transaction::with('book', 'user')
            ->orderBy(DB::raw('DATE(date_borrowed)'), 'desc')
            ->orderBy(DB::raw('TIME(date_borrowed)'), 'desc')
            ->get();
        return view('pdf.transaction-pdf-report-format', compact('data'));
    }
    public function search(Request $request)
    {
        $inputName      = $request->input('name');
        $fromInputDate  = $request->input('start');
        $toInputDate    = $request->input('end');
        $type           = $request->input('type');
        $validator = Validator::make($request->all(), [
            'start'         => 'sometimes',
            'end'           => 'sometimes',
            'last-name'     => 'sometimes',
            'first-name'    => 'sometimes',
            'type'          => 'sometimes|in:All,Borrowed,Reserved',
        ]);
        if ($validator->fails()) {
            return redirect()->back()->with('toast-warning', $validator->errors()->first());
        }
        if ($request->input('submit') == 'pdf') {
            $data = $this->generateData($request);
            $this->generatePDF($data, $type);
            return redirect()->route('report.transaction')->with('toast-success', 'Successfully exported to PDF');
        } else if ($request->input('submit') == 'excel') {
            $data = $this->generateData($request);
            $this->exportExcel($data);
            return redirect()->route('report.transaction')->with('toast-success', 'Successfully exported to Excel');
        }
        $data = $this->generateData($request);
        return view('report.transactions.transactions', compact('data', 'inputName', 'fromInputDate', 'toInputDate', 'type'));
    }
    private function generatePDF($data, $type)
    {
        $items = [
            'title'         => 'Transaction Report',
            'school'        => "Bicutan Parochial School, Inc.",
            'type'          => $type,
            'logo'          => base64_encode(file_get_contents((public_path('img/BPSLogo.png')))),
            'address'       => "Manuel L. Quezon St., Lower Bicutan, Taguig City",
            'user'          => Auth::user()->first_name . ' ' . Auth::user()->last_name,
            'date'          => date('F j, Y'),
            'data'          => $data,
            'totalCount'    => $data->count(),
        ];
        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isPhpEnabled', true);
        $options->set('isRemoteEnabled', true);
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml(view('pdf.transaction-pdf-report', $items));
        $dompdf->setPaper('legal', 'landscape');
        $dompdf->render();
        $dompdf->stream('transaction-report ' . date('Y-m-d') . '.pdf', array('Attachment' => true));
        exit;
    }
    private function exportExcel($data)
    {
        $spreadsheet    = new Spreadsheet();
        $logo           = new Drawing();
        $sheet          = $spreadsheet->getActiveSheet();
        
        $logo->setName('BPS Logo');
        $logo->setDescription('BPS Logo');
        $logo->setPath(public_path('img/BPSLogoFull.png'));
        $logo->setHeight(80);
        $logo->setCoordinates('B1');
        $logo->setOffsetX(300);
        $logo->setOffsetY(5);
        $logo->setWorksheet($sheet);

        $sheet->setTitle('Transaction Report');
        $sheet->getColumnDimension('A')->setWidth(20);
        $sheet->getColumnDimension('B')->setWidth(60);
        $sheet->getColumnDimension('C')->setWidth(30);
        $sheet->getColumnDimension('D')->setWidth(20);
        $sheet->getColumnDimension('E')->setWidth(20);
        $sheet->getColumnDimension('F')->setWidth(20);
        $sheet->getColumnDimension('G')->setWidth(20);
        $sheet->mergeCells('A7:G7');
        $sheet->mergeCells('A8:G8');
        $sheet->setCellValue('A7', 'Report Generated By: ' . Auth::user()->first_name . ' ' . Auth::user()->last_name);
        $sheet->setCellValue('A8', 'Report Generated On: ' . date('F j, Y'));
        $sheet->getStyle('A7:G8')->getFont()->setBold(true);
        $sheet->getStyle('A7:G8')->getFont()->setSize(10);
        $sheet->getStyle('A7:G8')->getAlignment()->setHorizontal('left');
        $sheet->getStyle('A7:G8')->getAlignment()->setVertical('left');
        $sheet->getStyle('A7:G8')->getAlignment()->setWrapText(true);
        $sheet->getStyle('A10:G10')->getFont()->setSize(12);
        $sheet->getStyle('A10:G10')->getFont()->setBold(true);
        $sheet->setCellValue('A10', 'Accession');
        $sheet->setCellValue('B10', 'Title');
        $sheet->setCellValue('C10', 'Name');
        $sheet->setCellValue('D10', 'Borrowed');
        $sheet->setCellValue('E10', 'Due');
        $sheet->setCellValue('F10', 'Returned');
        $sheet->setCellValue('G10', 'Status');
        $row = 11;
        foreach ($data as $item) {
            if(!$item->book || !$item->user) {
                continue; // Skip if book or user relationship is not loaded
            }
            $sheet->setCellValue('A' . $row, $item->book->accession);
            $sheet->setCellValue('B' . $row, $item->book->title);
            $sheet->setCellValue('C' . $row, $item->user->last_name . ', ' . $item->user->first_name . ' ' . $item->user->middle_name);
            $sheet->setCellValue('D' . $row, $item->date_borrowed);
            $sheet->setCellValue('E' . $row, $item->due_date ?? 'Not Set');
            $sheet->setCellValue('F' . $row, $item->return_date ?? 'Not Returned');
            $sheet->setCellValue('G' . $row, $item->transaction_type);
            $row++;
        }
        $writer     = new WriterXlsx($spreadsheet);
        $fileName = 'transaction-report ' . date('Y-m-d') . '.xlsx';
        header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        header("Content-Disposition: attachment;filename=\"$fileName\"");
        $writer->save("php://output");
        exit;
    }
    private function generateData(Request $request)
    {
        $fromInputDate  = $request->input('start');
        $toInputDate    = $request->input('end');
        $inputName      = strtolower($request->input('name'));
        $type           = $request->input('type');

        $query = Transaction::with('book', 'user');
        if (strlen($fromInputDate) > 0) {
            $fromInputDate = DateTime::createFromFormat('m/d/Y', $fromInputDate)->format('Y-m-d');
            $toInputDate = DateTime::createFromFormat('m/d/Y', $toInputDate)->format('Y-m-d');
            $query->whereBetween(DB::raw('DATE(date_borrowed)'), [$fromInputDate, $toInputDate]);
        }

        if (strlen($inputName) > 0) {
            $query->whereHas('user', function ($q) use ($inputName) {
                $q->where('first_name', 'like', '%' . $inputName . '%');
                $q->orWhere('middle_name', 'like', '%' . $inputName . '%');
                $q->orWhere('last_name', 'like', '%' . $inputName . '%');
                $q->orWhere(DB::raw('lower(concat(first_name, " ", middle_name, " ", last_name))'), 'like', '%' . $inputName . '%');
                $q->orWhere(DB::raw('lower(concat(middle_name, " ", last_name, ", ", first_name))'), 'like', '%' . $inputName . '%');
                $q->orWhere(DB::raw('lower(concat(last_name, ", ", first_name, " ", middle_name))'), 'like', '%' . $inputName . '%');
                $q->orWhere(DB::raw('lower(concat(last_name, ", ", first_name))'), 'like', '%' . $inputName . '%');
                $q->orWhere(DB::raw('lower(concat(first_name, " ", last_name))'), 'like', '%' . $inputName . '%');
            })->orWhereHas('book', function ($q) use ($inputName) {
                $q->where('title', 'like', '%' . $inputName . '%')
                    ->orWhere('accession', 'like', '%' . $inputName . '%');
            })->orWhere('transaction_type', 'like', '%' . $inputName . '%');
        }

        if ($type && $type !== 'All') {
            $query->orWhere('transaction_type', $type);
        }
        $data = $query->orderBy(DB::raw('DATE(date_borrowed)'), 'asc')
            ->get();
        return $data;
    }
}
